# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip and build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Install brukerapi (editable)
      run: |
        git clone https://github.com/isi-nmr/brukerapi-python.git
        cd brukerapi-python
        pip install -e .[dev]

    - name: Download test data from Zenodo
      run: |
        cd brukerapi-python/test
        zenodo_get 10.5281/zenodo.4522220

    - name: Test using the PV5.1 data set
      run: |
        cd brukerapi-python/test
        unzip 0.2H2.zip
        python -m pytest . --test_data "0.2H2" --test_suites="test_data" -v

    - name: Test using the PV6.0.1 data set
      run: |
        cd brukerapi-python/test
        unzip 20200612_094625_lego_phantom_3_1_2.zip
        python -m pytest --test_data "20200612_094625_lego_phantom_3_1_2"  --test_suites="test_data" -v

    - name: Test using the PV7.0.0 data set
      run: |
        cd brukerapi-python/test
        unzip 20210128_122257_LEGO_PHANTOM_API_TEST_1_1.zip
        python -m pytest --test_data "20210128_122257_LEGO_PHANTOM_API_TEST_1_1" --test_suites="test_data" -v